#!/usr/bin/env bash

is_installed() {
  command -v "$1" >/dev/null 2>&1
}

banner() {
  echo "=== $1 "
}

skipping_banner() {
  echo "=== skipping $1 - already installed"
}

# [[ Stow ]]
if ! is_installed stow; then
  banner "Installing stow"
  sudo apt update
  sudo apt install stow
else
  skipping_banner "stow"
fi

# [[ fish ]]
if ! is_installed fish; then
  banner "Installing fish"

  sudo apt-add-repository ppa:fish-shell/release-3
  sudo apt update
  sudo apt install fish
else
  skipping_banner "fish"
fi

# [[ eza ]]
if ! is_installed eza; then
  banner "Installing eza"

  sudo mkdir -p /etc/apt/keyrings
  wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
  echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
  sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
  sudo apt update
  sudo apt install -y eza
else
  skipping_banner "eza"
fi

# [[ bat ]]
if ! is_installed bat; then
  banner "Installing bat"

  sudo apt update
  sudo apt install -y bat
  ln -s /usr/bin/batcat ~/bin/bat 
else
  skipping_banner "bat"
fi
