#!/usr/bin/env bash

DOTFILES_DIR=$HOME/dotfiles

is_installed() {
  [ -z "$(dpkg -l | awk "/^ii  $1/")" ]
}

banner() {
  echo "=== $1 "
}

# Install stow if not already installed
if is_installed stow; then
  banner "Installing stow"
  sudo apt install stow
fi

banner "Configuring Bash"
rm ${HOME}/.bash_aliases
stow bash

banner "Configuring ~/bin"
mkdir -p "${HOME}/bin"
stow bin

banner "Configuring Tmux"
mkdir -p "${HOME}/.config/tmux"
stow tmux

banner "Configuring Alacritty"
mkdir -p "${HOME}/.config/alacritty"
stow alacritty

banner "Configuring Fish shell"
mkdir -p "${HOME}/.config/fish"
stow fish

banner "Configuring Ruby"
stow ruby
