"              "
"  Main Setup  "
"	             "

set nocompatible  " Vi is nothin' but a fossil.

let mapleader = ',' " use a comma instead of \. Load early

" I love you Pathogen! "
call pathogen#infect()

color jellybeans  " default theme
syntax on       " syntax highlighting

"                    "
"  Personal Globals  "
"                    "

let g:my_name="Christopher Clarke"
let g:my_email="beakr@ninjanizr.com" " buiseness email
let g:personal_email="beaker2000@me.com" " personal email
let g:my_blog="www.beakerblog.net"


"-------------------"
"        CORE       "
"-------------------"

set number
set ruler          " parse out what line & column your on
set rulerformat=%30(%=\:b%n%y%m%r%w\ %l,%c%V\ %P%)
set cursorline     " highlight current line cursor is on
set ttyfast        " fast terminal
set scrolloff=3
set encoding=utf-8 " encoding
set showcmd
set visualbell     " I'm a bit scared of smashing the computer if this is left on...

set wrap

  " get rid of the default godzilla tabs please
set tabstop=2
set shiftwidth=2
set softtabstop=2

set expandtab      " easily erase tabs a space at a time
set colorcolumn=85 " colorcolumn for wrapping purposes (bar at the side)
set listchars=tab:\ \ ,trail:·
set backspace=indent,eol,start " if there's nothing left to backspace, start backspacing the next line

" search
set hlsearch   " highlight search results
set incsearch  " don't keep hitting <enter> for your search
set ignorecase " case insensensitive searching
set smartcase  " if the search contains a capital letter, make it case sensitive

" tab completion
set wildmode=list:longest,list:full
set wildignore+=*.o,*.obj,.git,*.rbc,*.class,.svn,vendor/gems/*

" Get them .swp files outta' my sight!
set backupdir=~/.vim/backup
set directory=~/.vim/backup

"----------------"
" abbrivtiations "
"----------------"


"----------"
" mappings "
"----------"

" No arrow keys allowed
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>

nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>

" give your hands a break from the '==' command today
nnoremap = ==

" For these times when your cursor is on the last letter, but when you go in insert mode it's in between the last and second last letter
nnoremap a i<right>


" -------------------------------------------------------------------------
"                            Helpful Functions                            |
" -------------------------------------------------------------------------

" Show syntax highlighting groups for word under cursor
nmap <C-S-P> :call <SID>SynStack()<CR>
function! <SID>SynStack()
  if !exists("*synstack")
    return
  endif
  echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunc
