" -------------------------------------------------------------------------
"                                  Setup                                  |
" -------------------------------------------------------------------------

set nocompatible     " it's the 21st century

let mapleader = ','  " use , instead of \. Load early.

" use Pathogen.vim to load vim bundles
call pathogen#infect('~/src/vim_bundles')

color ir_black     " default colorscheme (gui set in .gvimrc)
syntax on          " syntax highlighting

" ensure vim always runs from a shell (hack to make ruby pick up rvm
" version when running Ruby from inside Vim
set shell=/bin/sh

" -------------------------------------------------------------------------
"                                 Globals                                 |
" -------------------------------------------------------------------------

let g:my_name="Steve Clarke"
let g:my_email="steve@seven7.ca"

" -------------------------------------------------------------------------
"                               Core Config                               |
" -------------------------------------------------------------------------

"set relativenumber " show how far away each line is from current one
set number
set ruler          " show line and column # of cursor position
set cursorline     " hightlight the line we're on
set ttyfast        " assume fast terminal
set scrolloff=3    " min. # of lines above and below the cursor
"set laststatus=2   " Status bar
set encoding=utf-8 " set encoding
set showcmd        " show (partial) command in the status line
set visualbell     " no annoying beep, please

" Whitespace stuff
set nowrap
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab      " convert tabs to spaces
set colorcolumn=85 " show a colored column to help with wrapping
" set color colum to sane color
hi ColorColumn guifg=#30312c guibg=#30312c
set list listchars=tab:\ \ ,trail:·
set backspace=indent,eol,start  " backspace over everything in insert mode

" Searching
set hlsearch   " highlight search results
set incsearch  " incremental search
set ignorecase " case-insensitive search unless...
set smartcase  " if search contains caps, make case-sensitive

" Tab completion
set wildmode=list:longest,list:full
set wildignore+=*.o,*.obj,.git,*.rbc,*.class,.svn,vendor/gems/*

" Use modeline overrides
set modeline
set modelines=10

" Directories for swp files
set backupdir=~/.vim/backup
set directory=~/.vim/backup
" set noswapfile  " Has anyone ever saved the day due to a .swp file???

" disable automatic commenting on subsequent lines
set formatoptions-=ro

" MacVIM shift+arrow-keys behavior (required in .vimrc)
let macvim_hig_shift_movement = 1

" -------------------------------------------------------------------------
"                              Key Mappings                               |
" -------------------------------------------------------------------------

" clear highlighting
nnoremap <leader>/ :noh<cr>

" help save an <esc> key today
inoremap jj <esc>

" <leader>a to :Align
vnoremap <leader>a :Align<space>

" Re-hardwrap paragraphs of text
vnoremap <leader>q gq       " in visual mode
nnoremap <leader>q gqip     " in normal mode

" Sane window switching
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l

" Run the current file through Ruby
map <Leader>r :w\|!ruby %<cr>

" Erase whitespace
map <Leader>fw :EraseBadWhitespace<cr>

" Fix tabs (retab)
map <Leader>ft :retab<cr>

" Insert comment box
map ,co O#<Esc>74A=<Esc>o#<Space><Esc>o#<Esc>74A=<Esc>kA

" -------------------------------------------------------------------------
"                              Plugin Config                              |
" -------------------------------------------------------------------------

" Without setting this, ZoomWin restores windows in a way that causes
" equal always behavior to be triggered the next time CommandT is used.
" This is likely a bludgeon to solve some other issue, but it works
set noequalalways

" ZoomWin configuration
map <Leader>w :ZoomWin<CR>

" NERDTree configuration
let NERDTreeIgnore=['\.pyc$', '\.rbc$', '\~$']
map <Leader>n :NERDTreeToggle<CR>

" Command-T configuration
let g:CommandTMaxHeight=20

" -------------------------------------------------------------------------
"                                Filetype                                 |
" -------------------------------------------------------------------------

function! s:setupWrapping()
  set wrap
  set wrapmargin=2
  set textwidth=72
endfunction

au BufRead,BufNewFile *.txt call s:setupWrapping()

function! s:setupMarkup()
  call s:setupWrapping()
  map <buffer> <Leader>p :Hammer<CR>
endfunction

" md, markdown, and mk are markdown and define buffer-local preview
au BufRead,BufNewFile *.{md,markdown,mdown,mkd,mkdn} call s:setupMarkup()

" Thorfile, Rakefile, Vagrantfile and Gemfile are Ruby
au BufRead,BufNewFile {Gemfile,Rakefile,Vagrantfile,Thorfile,config.ru} set ft=ruby

" add json syntax highlighting
au BufNewFile,BufRead *.json set ft=javascript

" load the plugin and indent settings for the detected filetype
filetype plugin indent on

" -------------------------------------------------------------------------
"                               Misc Config                               |
" -------------------------------------------------------------------------

" Remember last location in file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal g'\"" | endif
endif

" Include user's local vim config
if filereadable(expand("~/.vimrc.local"))
  source ~/.vimrc.local
endif
