#!/bin/bash

# Rails {VERSION} Upgrade Detection Script
# Generated by Rails Upgrade Assistant
# This script identifies code that needs updating for Rails {VERSION}

set -e

# Colors for output
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Output file
OUTPUT_FILE="rails_{VERSION_SLUG}_upgrade_findings.txt"

echo "================================================" | tee "$OUTPUT_FILE"
echo "Rails {VERSION} Upgrade - Breaking Changes Detection" | tee -a "$OUTPUT_FILE"
echo "Project: $(basename $(pwd))" | tee -a "$OUTPUT_FILE"
echo "Date: $(date)" | tee -a "$OUTPUT_FILE"
echo "================================================" | tee -a "$OUTPUT_FILE"
echo "" | tee -a "$OUTPUT_FILE"

# Function to check if command found results
check_results() {
  local count=$1
  local name=$2

  if [ "$count" -gt 0 ]; then
    echo -e "${RED}   ⚠️  Found: $count occurrences${NC}" | tee -a "$OUTPUT_FILE"
    return 0
  else
    echo -e "${GREEN}   ✅ None found${NC}" | tee -a "$OUTPUT_FILE"
    return 1
  fi
}

echo "🔴 HIGH PRIORITY - BREAKING CHANGES" | tee -a "$OUTPUT_FILE"
echo "===================================" | tee -a "$OUTPUT_FILE"
echo "" | tee -a "$OUTPUT_FILE"

# NOTE: {HIGH_PRIORITY_CHECKS} will be replaced by Claude with actual checks
# based on the patterns file for this specific Rails version

{HIGH_PRIORITY_CHECKS}

echo "" | tee -a "$OUTPUT_FILE"
echo "🟡 MEDIUM PRIORITY - DEPRECATIONS & CHECKS" | tee -a "$OUTPUT_FILE"
echo "==========================================" | tee -a "$OUTPUT_FILE"
echo "" | tee -a "$OUTPUT_FILE"

# NOTE: {MEDIUM_PRIORITY_CHECKS} will be replaced by Claude with actual checks
{MEDIUM_PRIORITY_CHECKS}

echo "" | tee -a "$OUTPUT_FILE"
echo "📊 PROJECT STATISTICS" | tee -a "$OUTPUT_FILE"
echo "====================" | tee -a "$OUTPUT_FILE"
echo "" | tee -a "$OUTPUT_FILE"

JOB_COUNT=$(find app/jobs -name "*_job.rb" 2>/dev/null | wc -l | tr -d ' ')
CONTROLLER_COUNT=$(find app/controllers -name "*_controller.rb" 2>/dev/null | wc -l | tr -d ' ')
MODEL_COUNT=$(find app/models -name "*.rb" 2>/dev/null | wc -l | tr -d ' ')
SERVICE_COUNT=$(find app/services -name "*.rb" 2>/dev/null | wc -l | tr -d ' ')
INITIALIZER_COUNT=$(ls config/initializers/*.rb 2>/dev/null | wc -l | tr -d ' ')

echo "Job files:              $JOB_COUNT" | tee -a "$OUTPUT_FILE"
echo "Controller files:       $CONTROLLER_COUNT" | tee -a "$OUTPUT_FILE"
echo "Model files:            $MODEL_COUNT" | tee -a "$OUTPUT_FILE"
echo "Service files:          $SERVICE_COUNT" | tee -a "$OUTPUT_FILE"
echo "Initializers:           $INITIALIZER_COUNT" | tee -a "$OUTPUT_FILE"
echo "" | tee -a "$OUTPUT_FILE"

echo "" | tee -a "$OUTPUT_FILE"
echo "🎯 SUMMARY" | tee -a "$OUTPUT_FILE"
echo "==========" | tee -a "$OUTPUT_FILE"
echo "" | tee -a "$OUTPUT_FILE"

# NOTE: {TOTAL_CALCULATION} will be replaced with actual total calculation
{TOTAL_CALCULATION}

if [ "$TOTAL_ISSUES" -eq 0 ]; then
  echo -e "${GREEN}✅ No breaking changes detected!${NC}" | tee -a "$OUTPUT_FILE"
  echo -e "${GREEN}   Your codebase looks ready for Rails {VERSION}${NC}" | tee -a "$OUTPUT_FILE"
else
  echo -e "${RED}⚠️  Found $TOTAL_ISSUES breaking change(s) that need fixing:${NC}" | tee -a "$OUTPUT_FILE"
  echo "" | tee -a "$OUTPUT_FILE"
  # NOTE: {ISSUE_SUMMARY} will be replaced with list of issues found
  {ISSUE_SUMMARY}
fi

echo "" | tee -a "$OUTPUT_FILE"
echo "📋 AFFECTED FILES (for Neovim)" | tee -a "$OUTPUT_FILE"
echo "==============================" | tee -a "$OUTPUT_FILE"
echo "" | tee -a "$OUTPUT_FILE"
echo "If you want to fix these interactively with Claude, open these files in Neovim:" | tee -a "$OUTPUT_FILE"
echo "" | tee -a "$OUTPUT_FILE"

# NOTE: {FILE_LIST_GENERATION} will be replaced with code to collect affected files
{FILE_LIST_GENERATION}

echo "" | tee -a "$OUTPUT_FILE"
echo "📝 REQUIRED CONFIGURATION UPDATES" | tee -a "$OUTPUT_FILE"
echo "==================================" | tee -a "$OUTPUT_FILE"
echo "" | tee -a "$OUTPUT_FILE"
echo "These files MUST be updated:" | tee -a "$OUTPUT_FILE"
echo "1. Gemfile - Update Rails version to {VERSION}" | tee -a "$OUTPUT_FILE"
echo "2. config/application.rb - Change load_defaults to {VERSION_SHORT}" | tee -a "$OUTPUT_FILE"
echo "" | tee -a "$OUTPUT_FILE"

echo "================================================" | tee -a "$OUTPUT_FILE"
echo "Detection complete!" | tee -a "$OUTPUT_FILE"
echo "================================================" | tee -a "$OUTPUT_FILE"
echo "" | tee -a "$OUTPUT_FILE"
echo "Full report saved to: $OUTPUT_FILE" | tee -a "$OUTPUT_FILE"
echo "" | tee -a "$OUTPUT_FILE"
echo "Next steps:" | tee -a "$OUTPUT_FILE"
echo "1. Review this report" | tee -a "$OUTPUT_FILE"
echo "2. Share findings with Claude for interactive help" | tee -a "$OUTPUT_FILE"
echo "3. Fix breaking changes" | tee -a "$OUTPUT_FILE"
echo "4. Run test suite" | tee -a "$OUTPUT_FILE"
echo "5. Re-run this script to verify all issues resolved" | tee -a "$OUTPUT_FILE"
echo "" | tee -a "$OUTPUT_FILE"

echo ""
echo -e "${BLUE}================================================${NC}"
echo -e "${BLUE}Report saved to: ${OUTPUT_FILE}${NC}"
echo -e "${BLUE}================================================${NC}"
echo ""

if [ "$TOTAL_ISSUES" -eq 0 ]; then
  echo -e "${GREEN}🎉 Great news! No breaking changes found.${NC}"
  echo -e "${GREEN}You still need to update config files, but no code changes needed.${NC}"
else
  echo -e "${YELLOW}⚠️  Found issues that need attention before upgrading.${NC}"
  echo -e "${YELLOW}Share the findings report with Claude for interactive help.${NC}"
fi

echo ""
