ZSH=$HOME/src/dotfiles/zsh

# load configs
for config_file ($ZSH/config/*.zsh) source $config_file

# load functions
fpath=($ZSH/functions $fpath)
for function_file ($ZSH/functions/*.zsh) source $function_file

# use a local config file if it exists
[[ -f ~/.localrc ]] && . ~/.localrc


PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
