-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Dell Inc. DELL S2721QS 3QL0M43",
  mode = "3840x2160@60.00",
  position = "2880x0",
  scale = 1.33,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Dell Inc. DELL S2721QS D0X1M43",
  mode = "3840x2160@60.00",
  position = "0x0",
  scale = 1.33,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Dell Inc. DELL S2721QS 3QL0M43", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:Dell Inc. DELL S2721QS 3QL0M43", persistent = true })
hl.workspace_rule({ workspace = "3", monitor = "desc:Dell Inc. DELL S2721QS 3QL0M43", persistent = true })
hl.workspace_rule({ workspace = "4", monitor = "desc:Dell Inc. DELL S2721QS D0X1M43", default = true, persistent = true })
hl.workspace_rule({ workspace = "5", monitor = "desc:Dell Inc. DELL S2721QS D0X1M43", persistent = true })
hl.workspace_rule({ workspace = "6", monitor = "desc:Dell Inc. DELL S2721QS D0X1M43", persistent = true })
