eval "$(rbenv init -)"

export DOTFILES_DIR=~/src/dotfiles

. $DOTFILES_DIR/bash/aliases
. $DOTFILES_DIR/bash/completions
. $DOTFILES_DIR/bash/config

# use a local-only file for stuff unique to this system
if [ -f ~/.bash_profile_local ]; then
  source ~/.bash_profile_local
fi
