export DOTFILES_DIR=~/src/dotfiles

. $DOTFILES_DIR/bash/aliases
. $DOTFILES_DIR/bash/completions
. $DOTFILES_DIR/bash/config

# use a local-only file for stuff unique to this system
if [ -f ~/.localrc ]; then
  source ~/.localrc
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
